export const en = {
  advanced: "Advanced",
  basic: "Basic",
  plugins: "Plugins",
  scenarios: "Scenarios",
  faq: 'FAQ & Best Practice',
  hotPlug: 'Hot Plug',
  hotPlugNote: 'Hot Plug Demo',
  basicVoiceCalling: 'Basic Voice Calling',
  basicVoiceCallingNote: 'A basic Voice Calling app',
  basicVideoCalling: 'Basic Video Calling',
  basicVideoCallingNote: 'A basic Video Calling app',
  basicLiveStreaming: 'Basic Live Streaming',
  basicLiveStreamingNote: 'A basic Interactive Live Streaming app, showing sample code for both Interactive Live Streaming Premium and Standard.',
  groupvideocalling: 'Group Video Calling',
  groupvideocallingNote: 'A group Video Calling app with the features of screen sharing, dual- stream mode, and adaptive layout.',
  selfRendering: 'Video Self- Rendering',
  selfRenderingNote: 'Video Self - Rendering Demo.',
  selfCapturing: 'Video Self - Capturing',
  selfCapturingNote: 'Video Self - Capturing Demo.',
  videoScreenshot: 'Video Screenshot',
  videoScreenshotNote: 'Video Screenshot Demo.',
  cloudProxy: 'Cloud Proxy',
  cloudProxyNote: 'Cloud Proxy Demo.',
  movietogether: 'Movie Together',
  movietogetherNote: 'Video Sharing and Real Time Engagement Demo.',
  testdevices: 'Test / Switch Media Devices',
  testdevicesNote: 'A Video Calling app with pre - call device test and in -call device switch.',
  adjustvideoprofile: 'Adjust Video Profile',
  adjustvideoprofileNote: 'A Video Calling app with the feature of changing the local video profile(the resolution, bitrate, and frame rate) during a call.',
  incallstats: 'Display In - call Statistics',
  incallstatsNote: 'A Video Calling app with in -call statistics. ',
  muteaudiovideosetmuted: 'Mute using setMuted API',
  muteaudiovideosetmutedNote: 'A Video Calling app with the feature of muting the local audio and stopping the local video.',
  muteaudiovideosetenabled: ' Mute using setEnabled API',
  muteaudiovideosetenabledNote: 'A Video Calling app with the feature of muting the local audio and stopping the local video.',
  muteaudiovideomediastreamtrackenabled: 'Mute using MediaStreamTrack.enabled property',
  muteaudiovideomediastreamtrackenabledNote: 'A Video Calling app with the feature of muting the local audio and stopping the local video.',
  sharescreen: 'Share the Screen',
  sharescreenNote: 'A Video Calling app with the feature of screen sharing. ',
  imageenhance: 'Image Enhancement',
  imageenhanceNote: 'A Video Calling app with the feature of image enhancement.',
  audioeffect: 'Audio Effects / Music Files',
  audioeffectNote: 'A Video Calling app with the feature of playing background music or audio effects. ',
  cdnstreaming: 'Push Streams to CDN',
  cdnstreamingNote: 'An Interactive Live Streaming app with the feature of pushing streams to CDN(Content Delivery Network). ',
  dualstream: 'Enable Dual - stream Mode',
  dualstreamNote: 'A Video Calling app that enables dual - stream mode. ',
  geofencing: 'Network Geofencing',
  geofencingNote: 'A Video Calling app that enables geofencing.After enabling geofencing, the SDK only connects to Agora servers within the specified region. ',
  multiplechannel: 'Join Multiple Channels',
  multiplechannelNote: 'Join two channels simultaneously and subscribe Streams from them.',
  customvideosource: 'Custom Video Source',
  customvideosourceNote: 'Usage for custom video track and switch with camera track.',
  virtualbackground: 'Virtual Background',
  virtualbackgroundNote: 'Add virtual background with AI for video track with a SDK plugin.',
  beauty: 'Image Enhancement',
  beautyNote: 'The basic image enhancement',
  aidenoiser: 'AI Denoiser',
  aidenoiserNote: 'Add a AI noiser for audio track with a SDK plugin.',
  spatialAudioExtention: 'Spatial Audio Extention',
  spatialAudioExtentionNote: 'The Spatial Audio extension is used together with the Agora Web SDK(v4.13.0 or later).',
  autoplay: 'Deal with Autoplay',
  autoplayNote: 'To prevent the webpage from playing sound without permission, most web browsers restrict the autoplay function: Autoplay with sound is blocked unless the user has interacted with the webpage.',
  stringuid: 'String user names',
  stringuidNote: 'Starting from v2.5, the uid parameter in the Client.join method can be set as either a number or a string.You can join a channel by calling the Client.join method and passing in a string uid.',
  legacywebdemo: 'Legacy Web Demo',
  legacywebdemoNote: 'We have legacy web demo about Web RTC SDK, Web RTM SDK, etc.',
  tryitnow: 'Try it now',
  viewthecode: 'View the code',
  doc: 'Doc',
  questionare: 'Is this page helpful?',
  login:"Login",
  logout: 'Logout',
  ssoText: 'Logging in...',
  okText: 'OK',
  cancelText: 'Cancel',
}


